### PR TITLE
Reduction buffer

### PR DESCRIPTION
**Pull request by yodada**
In this PR:
 - Shared persistent reduction buffer -- 1 element per tile. tile 0 will be in charge of combining and producing the final result
 - This PR fixes `dot` in #106 and parallelized the simple (reduce all) case in reductions (`sum`, `reduce`)

This PR depends on #106

### CODE REVIEW

**Review by vb000 — APPROVED** [review]

**Comment by yodada** [comment]
Tested on COSIM
```
tests/test_dot.py::test_torch_dot_1 PASSED                               [ 16%]
tests/test_dot.py::test_torch_dot_2 PASSED                               [ 33%]
tests/test_dot.py::test_torch_dot_non_contiguous PASSED                  [ 50%]
tests/test_dot.py::test_torch_dot_different_device_F XFAIL               [ 66%]
tests/test_dot.py::test_torch_dot_mismatching_shape_F XFAIL              [ 83%]
tests/test_dot.py::test_torch_dot_hypothesis PASSED                      [100%]
```

**Comment by cbatten** [comment]
Also tested on emulation right? :)

**Comment by yodada** [comment]
Of course! Travis did that for us ;)

**Comment by yodada** [comment]
```
tests/test_mean.py::test_torch_mean_1 PASSED                             [  2%]
tests/test_mean.py::test_torch_mean_2 PASSED                             [  5%]
tests/test_mean.py::test_torch_mean_3 PASSED                             [  8%]
tests/test_mean.py::test_torch_mean_4 PASSED                             [ 11%]
tests/test_mean.py::test_torch_mean_5 PASSED                             [ 14%]
tests/test_mean.py::test_torch_mean_6 PASSED                             [ 17%]
tests/test_mean.py::test_torch_mean_7 PASSED                             [ 20%]
tests/test_mean.py::test_torch_mean_8 PASSED                             [ 23%]
tests/test_mean.py::test_torch_mean_9 PASSED                             [ 26%]
tests/test_mean.py::test_torch_mean_10 PASSED                            [ 29%]
tests/test_mean.py::test_torch_mean_11 PASSED                            [ 32%]
tests/test_mean.py::test_torch_mean_12 PASSED                            [ 35%]
tests/test_mean.py::test_torch_mean_13 PASSED                            [ 38%]
tests/test_mean.py::test_torch_mean_14 PASSED                            [ 41%]
tests/test_mean.py::test_torch_mean_15 PASSED                            [ 44%]
tests/test_mean.py::test_torch_mean_16 PASSED                            [ 47%]
tests/test_mean.py::test_torch_mean_17 PASSED                            [ 50%]
tests/test_mean.py::test_torch_mean_18 PASSED                            [ 52%]
tests/test_mean.py::test_torch_mean_19 PASSED                            [ 55%]
tests/test_mean.py::test_torch_mean_20 PASSED                            [ 58%]
tests/test_mean.py::test_torch_mean_21 PASSED                            [ 61%]
tests/test_mean.py::test_torch_mean_22 PASSED                            [ 64%]
tests/test_mean.py::test_torch_mean_23 PASSED                            [ 67%]
tests/test_mean.py::test_torch_mean_24 PASSED                            [ 70%]
tests/test_mean.py::test_torch_mean_25 PASSED                            [ 73%]
tests/test_mean.py::test_torch_mean_26 PASSED                            [ 76%]
tests/test_mean.py::test_torch_mean_27 PASSED                            [ 79%]
tests/test_mean.py::test_torch_mean_28 PASSED                            [ 82%]
tests/test_mean.py::test_torch_mean_29 PASSED                            [ 85%]
tests/test_mean.py::test_torch_mean_30 PASSED                            [ 88%]
tests/test_mean.py::test_torch_mean_31 PASSED                            [ 91%]
tests/test_mean.py::test_torch_mean_32 PASSED                            [ 94%]
tests/test_mean.py::test_torch_mean_33 PASSED                            [ 97%]
tests/test_mean.py::test_torch_mean_nan PASSED                           [100%]

======================== 34 passed in 203.85s (0:03:23) ========================

tests/test_sum.py::test_torch_sum_1 PASSED                               [  3%]
tests/test_sum.py::test_torch_sum_2 PASSED                               [  6%]
tests/test_sum.py::test_torch_sum_3 PASSED                               [  9%]
tests/test_sum.py::test_torch_sum_4 PASSED                               [ 12%]
tests/test_sum.py::test_torch_sum_5 PASSED                               [ 15%]
tests/test_sum.py::test_torch_sum_6 PASSED                               [ 18%]
tests/test_sum.py::test_torch_sum_7 PASSED                               [ 21%]
tests/test_sum.py::test_torch_sum_8 PASSED                               [ 24%]
tests/test_sum.py::test_torch_sum_9 PASSED                               [ 27%]
tests/test_sum.py::test_torch_sum_10 PASSED                              [ 30%]
tests/test_sum.py::test_torch_sum_11 PASSED                              [ 33%]
tests/test_sum.py::test_torch_sum_12 PASSED                              [ 36%]
tests/test_sum.py::test_torch_sum_13 PASSED                              [ 39%]
tests/test_sum.py::test_torch_sum_14 PASSED                              [ 42%]
tests/test_sum.py::test_torch_sum_15 PASSED                              [ 45%]
tests/test_sum.py::test_torch_sum_16 PASSED                              [ 48%]
tests/test_sum.py::test_torch_sum_17 PASSED                              [ 51%]
tests/test_sum.py::test_torch_sum_18 PASSED                              [ 54%]
tests/test_sum.py::test_torch_sum_19 PASSED                              [ 57%]
tests/test_sum.py::test_torch_sum_20 PASSED                              [ 60%]
tests/test_sum.py::test_torch_sum_21 PASSED                              [ 63%]
tests/test_sum.py::test_torch_sum_22 PASSED                              [ 66%]
tests/test_sum.py::test_torch_sum_23 PASSED                              [ 69%]
tests/test_sum.py::test_torch_sum_24 PASSED                              [ 72%]
tests/test_sum.py::test_torch_sum_25 PASSED                              [ 75%]
tests/test_sum.py::test_torch_sum_26 PASSED                              [ 78%]
tests/test_sum.py::test_torch_sum_27 PASSED                              [ 81%]
tests/test_sum.py::test_torch_sum_28 PASSED                              [ 84%]
tests/test_sum.py::test_torch_sum_29 PASSED                              [ 87%]
tests/test_sum.py::test_torch_sum_30 PASSED                              [ 90%]
tests/test_sum.py::test_torch_sum_31 PASSED                              [ 93%]
tests/test_sum.py::test_torch_sum_32 PASSED                              [ 96%]
tests/test_sum.py::test_torch_sum_33 PASSED                              [100%]

======================== 33 passed in 188.61s (0:03:08) ========================
```

**Pull request merged**
