### PR TITLE
sddmm (hammerblade, not CPU)

### PR DESCRIPTION
**Pull request by andrewpareles**
branch off of master (instead of sparse)

### CODE REVIEW

**Comment by yodada** [comment]
Is this PR ready to be reviewed?

**Comment by zzy82518996** [comment]
> Is this PR ready to be reviewed?

**Comment by zzy82518996** [comment]
Andrew and I decided to first send PR to my pytorch-spare-workload branch and merge to master together.

**Comment by yodada** [comment]
Sounds awesome ;)

**Pull request closed without merging**
