### PR TITLE
Jlw422 sigmoid

### PR DESCRIPTION
**Pull request by jweber97**
sigmoid kernel passes all testing including hypothesis in emul and cosim

### CODE REVIEW

**Comment by yodada** [comment]
Looks like we have an error
```
hammerblade/torch/kernel/kernel_sigmoid.cpp:18:5: error: ‘brg_elementwise_for’ was not declared in this scope
```
So recently we changed ‘brg_elementwise_for’ to `hb_parallel_foreach` ;)

**Comment by yodada** [comment]
Also, it seems there are *real* tabs in your code.

**Comment by jweber97** [comment]
What is it supposed to be instead of tabs?

**Review by yodada — APPROVED** [review]
LGTM! Awesome work! 
the failures in Travis is not related to your code, so dont worry about them!

**Comment by yodada** [comment]
Workaround added in #68

**Pull request merged**
