### PR TITLE
mlp_mnist tests

### PR DESCRIPTION
**Pull request by yodada**
Forward and backward tests for mlp mnist model

### CODE REVIEW

**Review by vb000 — APPROVED** [review]
Looks great!

**Comment by cbatten** [comment]
Does this mean we want to put workloads in the hb-torch repo? Maybe yes? Maybe we should just have a top-level directory called workloads or apps where we put all of our workloads in a clean an stylized way?

**Comment by yodada** [comment]
This one is not a real workload. The tests are only meant for testing the kernels used by mlp mnist. It does not download MNIST dataset, and it does not load any real parameters.

we can certainly put our workloads in the pytorch repo, if that makes more sense.

**Comment by cbatten** [comment]
Ah I see ... I like this idea. We have simple tests in pytorch for all kernels we use in workloads. That way we know the kernels work before we try out the workload ... I think keeping the full workloads (download MNIST, etc) should be in a separate repo ... but I do think every workload should have some corresponding end-to-end tests with simple parameters

**Comment by yodada** [comment]
In the our tests (mlp_mnist and lenet), the models are initialized with random parameters, and we do run them end-to-end. ;)

for example
https://github.com/cornell-brg/hb-pytorch/blob/5aae897bf5d27cd3001e1fc4963238a100a4d310/hammerblade/torch/tests/test_mlp_mnist.py#L88-L92
https://github.com/cornell-brg/hb-pytorch/blob/5aae897bf5d27cd3001e1fc4963238a100a4d310/hammerblade/torch/tests/test_mlp_mnist.py#L102-L104

**Comment by cbatten** [comment]
Perfect!

**Pull request merged**
