### PR TITLE
[emul] bring back emulation layer debug print

### PR DESCRIPTION
**Pull request by yodada**
This PR brings back the `Emulation layer enqueued kernel xxxx` prints, but only if set `EMUL_DEBUG` environment variable.

### CODE REVIEW

**Comment by yodada** [comment]
wait what??? the flake8 failures are not even in the changeset ... we never touched them ...

**Review by vb000 — APPROVED** [review]
Great! This is more convenient I guess! We could enable/disable messages with:

```
$ <EMUL_DEBUG=1> python setup.py install
```

**Comment by vb000** [comment]
Might be a good idea to mention this easter egg in the readme...

**Comment by cbatten** [comment]
Maybe all environment variables that control either emulation or cosim should have some kind of prefix to avoid namespace collisions? Maybe `HBEMUL_` or `HBCOSIM_` ? so it would be `HBEMUL_DEBUG=1` or like `HBCOSIM_LOG_FILE=dirforlogfiles` stuff like that?

**Comment by yodada** [comment]
Ok! We can do `HBEMUL_DEBUG=1`

**Pull request merged**
