### PR TITLE
README: Install hypothesis in the emulation instructions

### PR DESCRIPTION
**Pull request by sampsyo**
This adds `hypothesis` to the `pip install` line in the emulation instructions, as it already is in the cosim instructions.

Any interest in using [Poetry](https://python-poetry.org) to manage the virtualenv and dependencies? That would avoid the need to maintain separate lists of commands in the README, avoid requiring developers to copy & paste long commands like this, and combine the virtualenv creation and dependency installation into a single step.

### CODE REVIEW

**Review by vb000 — APPROVED** [review]

**Comment by vb000** [comment]
Arghh, `nan` failure! Not sure what's the reason for that. 

@zzy82518996 any thoughts on this travis failure?

**Comment by vb000** [comment]
Poetry sounds interesting to me. I read that `venv` is not that great with dependency resolution either. That's way `conda` got popular, I believe. 

Poetry claims to solves those issues as well, and being an open-source option, it's is even more appealing.

**Comment by yodada** [comment]
@zzy82518996 I remember seeing empty_path2 failed on cosim #25 .

**Comment by yodada** [comment]
Ok apparently `torch.equal` returns `False` when comparing `NaN` to `NaN`
```python
Python 3.6.8 (default, May  2 2019, 20:40:44)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> x = torch.tensor(nan)
>>> x
tensor(nan)
>>> h = x.hammerblade()
>>> h
tensor(nan, device='hammerblade')
>>> torch.equal(x, h.cpu())
False
``` 
we should use `allclose` with `equal_nan=True` https://pytorch.org/docs/stable/torch.html#torch.allclose

**Comment by zzy82518996** [comment]
Yes, I think Lin is right, this is also an issue in PR #25. I am not sure why it doesn't pass. I don't have this problem on my machine...

----- 原始邮件 -----
发件人: "Bandhav Veluri" <notifications@github.com>
收件人: "cornell-brg/hb-pytorch" <hb-pytorch@noreply.github.com>
抄送: "zzy82158996" <zzy82158996@sjtu.edu.cn>, "Mention" <mention@noreply.github.com>
发送时间: 星期五, 2020年 4 月 03日 下午 8:19:03
主题: Re: [cornell-brg/hb-pytorch] README: Install hypothesis in the emulation instructions (#47)

Arghh, `nan` failure! Not sure what's the reason for that. 

@zzy82518996 any thoughts on this travis failure?

**Comment by zzy82518996** [comment]
So we should aslo use allclose instead of equal ? May I ask what is Nan mean ?

----- 原始邮件 -----
发件人: "Lin Cheng" <notifications@github.com>
收件人: "cornell-brg/hb-pytorch" <hb-pytorch@noreply.github.com>
抄送: "zzy82158996" <zzy82158996@sjtu.edu.cn>, "Mention" <mention@noreply.github.com>
发送时间: 星期五, 2020年 4 月 03日 下午 8:37:30
主题: Re: [cornell-brg/hb-pytorch] README: Install hypothesis in the emulation instructions (#47)

Ok apparently `torch.equal` returns `False` when comparing `NaN` to `Nan`
```python
Python 3.6.8 (default, May  2 2019, 20:40:44)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-36)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> x = torch.tensor(nan)
>>> x
tensor(nan)
>>> h = x.hammerblade()
>>> h
tensor(nan, device='hammerblade')
>>> torch.equal(x, h.cpu())
False
``` 
we should use `allclose` with `equal_nan=True` https://pytorch.org/docs/stable/torch.html#torch.allclose

**Comment by yodada** [comment]
Ok I think we understand what leads to that failure. I gonna "force merge" this one.

**Comment by sampsyo** [comment]
> Poetry sounds interesting to me. I read that `venv` is not that great with dependency resolution either. That's way `conda` got popular, I believe.
> 
> Poetry claims to solves those issues as well, and being an open-source option, it's is even more appealing.

Right—conda is a whole "parallel universe" where everything is different. Poetry uses "normal" Python packages; it basically just automates what we're already doing.

**Comment by sampsyo** [comment]
> May I ask what is Nan mean ?

Hi, @zzy82518996! NaN means [not a number](https://en.wikipedia.org/wiki/NaN), and it's a special kind of floating-point value that represents the results of invalid computations.

**Comment by zzy82518996** [comment]
Yes, I got it. Thanks for letting me know that.

----- 原始邮件 -----
发件人: "Adrian Sampson" <notifications@github.com>
收件人: "cornell-brg/hb-pytorch" <hb-pytorch@noreply.github.com>
抄送: "zzy82158996" <zzy82158996@sjtu.edu.cn>, "Mention" <mention@noreply.github.com>
发送时间: 星期六, 2020年 4 月 04日 上午 10:14:20
主题: Re: [cornell-brg/hb-pytorch] README: Install hypothesis in the emulation instructions (#47)

> May I ask what is Nan mean ?

Hi, @zzy82518996! NaN means [not a number](https://en.wikipedia.org/wiki/NaN), and it's a special kind of floating-point value that represents the results of invalid computations.

**Pull request merged**
