### PR TITLE
Floor kernel

### PR DESCRIPTION
**Pull request by mchao409**
Implemented floor kernel.

### CODE REVIEW

**Review by yodada — APPROVED** [review]
LGTM! Thank you so much!

**Comment by yodada** [comment]
Looks like `Travis - Branch` checking is missing. I assume it is because this PR is from a forked repo? Anyways, I'm merging in this one.

**Comment by cbatten** [comment]
can we make sure that travis runs on all branches too?

**Comment by yodada** [comment]
It does, if the branch is in our repo. This branch comes from a forked repo

**Pull request merged**
