### PR TITLE
Indexing refactor

### PR DESCRIPTION
**Pull request by vb000**
Updated HammerBlade Tensor's indexing operator overloading to access tensors using `w[{...}]` instead of `w(...)`.

### CODE REVIEW

**Comment by cbatten** [comment]
Look. We need to have and actual design discussion about how we want to write clean close in the kernels. Let’s not just have everyone going off and implementing different versions.

**Comment by yodada** [comment]
So what is the plan? Delay this one until we have a formal discussion?

**Comment by cbatten** [comment]
Yes. I think we should discuss and come up with a plan of action for how to: (1) cleanly iterate over HB tensors in device code; and (2) cleanly refactor iteration code into a templated parallel_for style function in such a way that we can support loop unrolling, prefetching, etc

**Comment by vb000** [comment]
> Look. We need to have and actual design discussion about how we want to write clean close in the kernels. Let’s not just have everyone going off and implementing different versions.

We are discussing this here: https://github.com/cornell-brg/hb-pytorch/issues/54. This pr is attempt to address the concern you raised about `()` vs `[]` -- I didn't randomly chose to change it...

**Pull request closed without merging**
